### ISSUE TITLE
音刺激の周波数など

### ISSUE THREAD

**Issue by WATANABEMe** [temochiz-lab/tuexp2023#15]
音刺激の記述に使用する周波数，音色について，以前教えていただいたのを失念してしまったので，もう一度，ご教示いただけますか？すいません。

**Comment by temochiz-lab** [comment]
自分も完全に忘れていました💦
過去のメモによると、Windows PowerShell のbeepで生成した440Hzです。
https://github.com/temochiz-lab/tuexp2023/blob/main/watanabe-2023-lesson2-2/voice/%E4%BD%9C%E6%88%90%E6%96%B9%E6%B3%95.txt

**Comment by WATANABEMe** [comment]
ありがとうございました。
