### ISSUE TITLE
2-1プログラム　秒数を提示してカウント開始まで200msec

### ISSUE THREAD

**Issue by WATANABEMe** [temochiz-lab/tuexp2023#18]
2-1プログラムについて
キーを押すまでの時間をカウントするのを開始するのは、文字が提示された瞬間からですよね？
、10秒と提示して10秒をカウントし始めるのに、文字を認識する時間が100-200mseは必要なので、秒数の文字がでてから、カウントスタート時間を0.2秒ぐらいもうけられないかとおもうのですが、いかがでしょうか？
10秒（提示）－スタート（提示カウント開始）みたいには？

**Comment by temochiz-lab** [comment]
2-1ですよね?
jsPsychの仕組でその動きはできないので計測時間を加工するのが良いと思います。
この時に、
計測値、加工値(計測値-200msec)
みたいにデータに併記しても良いんですが、Excelで手動で加工した方が事由にできて良いような気が、、

**Comment by WATANABEMe** [comment]
承知しました。
一律に200msec引くのであれば，文字の認識の個人差もこみで分析する，ということにしたほうがいいですね。
今回はそれでいきます。明日から実験なので。
文字提示－マスク提示-反応時間ができたとおもうのですが，
文字提示（2秒）-ホワイトマスク提示から反応までの反応時間をとる，というのは，卒業生の三村さんはやってなかったでしょうか。

**Comment by temochiz-lab** [comment]
それが、、三村さんんのプログラムが残っていなくて確認取れず、、
2021年でしたっけ？ その年は木村さんのプログラムは残っているのですが。
結果的に使わず残してもいなかったような気もするんですが、思い出せずです..

「文字提示（2秒）-ホワイトマスク提示から反応までの反応時間をとる」でれば、
教示文を適切に書くことでできそうです。

**Comment by WATANABEMe** [comment]
[script_250nj.txt](https://github.com/temochiz-lab/tuexp2023/files/13200548/script_250nj.txt)

三村さんの250msect提示版です

**Comment by WATANABEMe** [comment]
2－1のプログラムは，今，実験中なので変更せず，2－3として改訂版の作成をお願いします。
文字提示（2秒）のあと，＋（凝視点）を出した時点からキーを押すまでの反応時間の計測できるように，
でお願いできますでしょうか。
よろしくお願いします。

**Comment by temochiz-lab** [comment]
かなり記憶が欠落していてプログラムを読んだところ
  trials.timeline.push(eyepoint) ; // 凝視点    3000msec
  trials.timeline.push(expA) ;     // 画像1表示  250msec
  trials.timeline.push(mask);      // マスク    1000msec
  trials.timeline.push(expB) ;     // 画像2表示  fjを押すまで計測
という流れになっていました。

新しい仕様としては。
・文字提示(2000msec)  例: "5秒"
・凝視点＋が表示、ここから計測開始で、キーを押すと凝視点も消える
で、合ってますでしょうか？

**Comment by WATANABEMe** [comment]
はい，
・文字提示(2000msec) 例: "5秒"
・凝視点＋が表示、ここから計測開始で、キーを押すと凝視点も消える

このような流れでお願いいたします。

**Comment by temochiz-lab** [comment]
了解しました。
次回打ち合わせくらいまでを目安に作ります。

**Comment by temochiz-lab** [comment]
教示文ですが、以下の修正でどうでしょうか？

現行
 1500 msec の凝視点の後に秒数が表示されます。表示された秒数が経過したらスペースキーを押してください。

修正
2秒の指定秒数の表示の後に1.5秒の凝視点が表示されます。　凝視点が消えた後に指定秒数が経過したらスペースキーを押してください。

**Comment by WATANABEMe** [comment]
「カウントしていただく秒数の文字表示の後に＋の凝視点が表示されます。凝視点が消えた後，文字表示の秒数が経過したと思ったら，スペースキーを押してください。」

としてください。
凝視点などが何秒表示されているかがわかってしまうと，カウントするときの手がかりになってしまうので，秒数は記載しないことにします。

**Comment by temochiz-lab** [comment]
了解です！

**Comment by temochiz-lab** [comment]
一旦、この通りで作ってみました。
https://temochiz-lab.github.io/tuexp2023/watanabe-2023-lesson2-1b/

ちょっとわかりにくい気がしていて、スペースキーを押した後に、そのまま次の問題に行くのですが、
この時に「キーが押されました」的な画面表示が無いと動いているのかどうかわからないかもしれないです。
練習セッションがあるから大丈夫なのかな、、

**Comment by WATANABEMe** [comment]
たしかに，少しわかりにくいので，次のように変更することはできますか？

「カウントしていただく秒数の文字表示の後に＋の凝視点が表示されます。＋が表示されたら，すぐに文字表示の秒数をカウントしてください。カウントが終了したら，スペースキーを押してください。スペースキーをおしたら，＋が消えます。」

**Comment by temochiz-lab** [comment]
望月案はこちらになります。
後ほどのミーティングで実際にの画面表示を比べて決定しましょう。

カウントしていただく秒数が文字で表示された後に「＋」の凝視点が表示されるので、秒数をカウントしてください。<br>カウントが終了したらスペースキーを押してください。　「＋」が消えて次の問題に進みます。

**Comment by temochiz-lab** [comment]
その後、問題呈示2000msecでも短い感じでなので、3000msecにしてみました。

**Comment by WATANABEMe** [comment]
集中してないと3000ｍｓぐらいがいいかもしれませんが，秒数カウントまでが集中していると長く感じてしまうので，
なかをとって，2500ｍｓではいかがでしょうか？

記憶課題での単語の提示の時は，2500ｍｓだったと思います。

**Comment by temochiz-lab** [comment]
修正しました。
https://github.com/temochiz-lab/tuexp2023/blob/main/watanabe-2023-lesson2-1b/script.js#L172
https://github.com/temochiz-lab/tuexp2023/blob/main/watanabe-2023-lesson2-1b/script.js#L249

こちらから確認できます。
https://temochiz-lab.github.io/tuexp2023/watanabe-2023-lesson2-1b/

**Comment by WATANABEMe** [comment]
確認しました。これでいいと思います。ありがとうございました。
