### ISSUE TITLE
結果のファイルについて

### ISSUE THREAD

**Issue by WATANABEMe** [temochiz-lab/tuexp2023#19]
結果のファイルで，不要なところは，書き込まないでおくことは可能でしょうか？

たとえば，2－1の実験で必要なのは，こういうデータなのですが（刺激表示をミリ単位に入力したのは，私の手入力作業です）
[22300041.xlsx](https://github.com/temochiz-lab/tuexp2023/files/13277161/22300041.xlsx)

**Comment by temochiz-lab** [comment]
これは出力をコントロールしている文書が無いのでやっている人はいないと思います。
技術的には可能かもしれないのですが、それぞれのExtentionの仕様を見ながら結果の変数を操作するということで、工数が非常に大きくなる上に、バージョンが変わるごとに作り直す可能性があります。
そこで頑張るのなら、jsPsychを使わずに自前でプログラムを作る方向の方が現実的かなと..

**Comment by WATANABEMe** [comment]
承知いたしました。
jsPsychでやるほうが，全体的には簡単ですから，いまのままでいきましょう。

**Comment by temochiz-lab** [comment]
了解しました。　issueをクローズします。
